### ISSUE TITLE
Switch to noble for ECDSA

### ISSUE THREAD

**Issue by jasny** [ltonetwork/lto-api.js#107]
Currently we're using tweetnacl for ED25519 and a custom build of jsrsasign for ECDSA. We should consider using a [elliptic](https://www.npmjs.com/package/elliptic) instead, which support ed25519, secp256k1 and secp256r1.

The library provides a much more low level implementation, so it's not a drop-in replacement.

**Comment by paulmillr** [comment]
elliptic is not secure. Use noble-curves instead.

**Comment by jasny** [comment]
See #111

**Comment by jasny** [comment]
Fixed in #111
